### ISSUE TITLE
Not working as expected in blender 3.4

### ISSUE THREAD

**Issue by manjunath7472** [mrachinskiy/commotion#28]
Second set of selected Keyframes not offsetting as expected if there are first set of keyframes.

**Comment by mrachinskiy** [comment]
Hi, could you please provide example blend file, or screenshot of the issue?

**Comment by MADREVV** [comment]
![image](https://user-images.githubusercontent.com/122756034/212571162-a38edd2f-c01e-4e44-be85-99ab91da7c65.png)
(Blender 3.3.2)

**Comment by mrachinskiy** [comment]
@MADREVV your issue is irrelevant to the initial report, next time open a new issue.

If error occurs on add-on activation, it means you are trying to install add-on repository instead of release. Make sure you download add-on release using link provided in [step one of installation guide](https://github.com/mrachinskiy/commotion#how-to-install).

No response from issue author, closing report as invalid.
